export let Events = {
    ssChanged: 0,
    entityAdded: 1,
    entityRemoved: 2,
    entityChanged: 3,
    cameraStateChanged: 4,
    prodDragging: 5,
    designClosed: 6,
    designOpened: 7,
    objLoaded: 8,
    projectLoaded: 9,
    designCreated: 10,
    prodTransformStarted: 11,
    prodTransformEnded: 12,
    cameraChangeStarted: 13,
    cameraChangeEnded: 14,
    designSaved: 15,
    prodCleared: 16,
    fontLoaded: 17,
    cameraUpdated: 18,
    cameraChanging: 19,
    frameRendered: 20,
    designReady: 21,
    roomNavigated: 22,
    prodLoaded: 23,
    materialApplied: 24,
    viewrepActivated: 25,
    prodPostLoad: 26,
    entityInfoChanged: 27,
    designChanged: 28,
    designUpdating: 29,
    elementChanged: 30,
    elementTransformStarted: 31,
    elementTransformEnded: 32,
    viewerSwitchStart:33,
    viewerSwitchEnd:34,
    entityPendingToDraw: 35,
    entityDragStarted: 36,
    entityDragEnded: 37,
    displayFloorSlab: 38,
    designWillClose: 39,
    cameraEnablePan: 40,
    cameraChangeStartedWithDelay: 41,
    canvasResized: 42,
    fitView: 43
}
